In [17]:
import numpy as np
import pandas as pd

LEXICON_LIST = ["ID-OpinionWords", "InSet", "vania"]

pos = pd.read_csv("Lexicon/vania/positive.txt", header=None, names=['pos'])
list_pos = pos['pos'].tolist()
neg = pd.read_csv("Lexicon/vania/negative.txt", header=None, names=['neg'])
list_neg = neg['neg'].tolist()

df = pd.read_csv("C:/Users/Samuel Samosir/Documents/Python/Kuliah/TA/benchmarking-sentiment-analysis-teks-indonesia/Dataset/clean/cleaned_posneg_Dataset_A_HT_200.csv", delimiter=";", low_memory=False, header=0)
df
# new_header = df.iloc[0] #grab the first row for the header
# df = df[1:] #take the data less the header row
# df.columns = new_header #set the header row as the df header

     Unnamed: 0                                               teks  label
0             0  ['juga', 'siap', 'penjara', 'ahok', 'dukung', ...      0
1             1  ['kawal', 'terus', 'pantau', 'terus', 'habis',...      0
2             2  ['juang', 'umat', 'islam', 'baru', 'mulai', 's...      0
3             3  ['kawal', 'pasti', 'ahok', 'masuk', 'bui', 'pe...      0
4             4  ['pun', 'kalian', 'kalian', 'bebas', 'politik'...      0
..          ...                                                ...    ...
193         194      ['percaya', 'adil', 'menang', 'ahok', 'ahok']      1
194         195  ['ahok', 'tolak', 'pecah', 'belah', 'indonesia...      1
195         196  ['orang', 'benci', 'tidak', 'pantas', 'kita', ...      1
196         197  ['ribut', 'sama', 'mungkin', 'ahok', 'sangka',...      1
197         199  ['ahok', 'salah', 'kalau', 'stuck', 'tata', 'b...      1

[198 rows x 3 columns]

In [18]:
emosi = ["positif", "negatif"]
fitur_sentimen_all = []

for tweet in df["teks"].tolist():
    # inisiasi value
    value = [0, 0]
    emosi_value = {}
    for i in range(len(emosi)):
        emosi_value[emosi[i]] = value[i]

    list_kata = eval(tweet)
    for k in list_kata:
        if k in list_pos:
            emosi_value["positif"] += 1
        if k in list_neg:
            emosi_value["negatif"] += 1

    fitur_sentimen_perkalimat = list(emosi_value.values())
    fitur_sentimen_all.append(fitur_sentimen_perkalimat)

fitur_sentimen_all, emosi

([[0, 0],
  [0, 0],
  [0, 0],
  [0, 0],
  [1, 0],
  [2, 1],
  [1, 0],
  [0, 1],
  [0, 0],
  [0, 1],
  [1, 0],
  [0, 0],
  [1, 0],
  [0, 0],
  [1, 0],
  [0, 1],
  [0, 0],
  [0, 0],
  [0, 1],
  [0, 0],
  [0, 1],
  [0, 0],
  [0, 0],
  [0, 0],
  [0, 1],
  [0, 1],
  [0, 0],
  [0, 0],
  [0, 0],
  [0, 1],
  [0, 0],
  [3, 0],
  [1, 1],
  [0, 0],
  [0, 0],
  [0, 0],
  [0, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [0, 1],
  [0, 0],
  [0, 1],
  [0, 0],
  [0, 0],
  [1, 0],
  [0, 0],
  [0, 0],
  [0, 0],
  [0, 0],
  [0, 3],
  [0, 1],
  [0, 0],
  [0, 0],
  [0, 0],
  [0, 0],
  [1, 1],
  [1, 1],
  [0, 0],
  [0, 0],
  [0, 0],
  [0, 0],
  [0, 1],
  [0, 1],
  [1, 0],
  [0, 1],
  [0, 0],
  [2, 0],
  [0, 0],
  [0, 0],
  [1, 0],
  [0, 1],
  [0, 0],
  [0, 0],
  [0, 0],
  [0, 0],
  [1, 0],
  [1, 0],
  [0, 0],
  [2, 0],
  [0, 1],
  [1, 0],
  [0, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [0, 0],
  [0, 0],
  [0, 0],
  [1, 0],
  [0, 0],
  [0, 0],
  [0, 0],
  [2, 1],
  [0, 0],
  [0, 0],
  [2, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [1, 0],
  [2, 0],
  [1, 0],
  [0, 0],
  [1, 0],
  [1, 0],
  [0, 0],
  [2, 0],
  [1, 0],
  [2, 0],
  [0, 0],
  [1, 0],
  [1, 0],
  [0, 1],
  [0, 0],
  [0, 0],
  [1, 0],
  [2, 0],
  [0, 0],
  [0, 0],
  [3, 0],
  [0, 2],
  [0, 0],
  [0, 0],
  [0, 0],
  [0, 0],
  [0, 0],
  [0, 0],
  [1, 0],
  [0, 0],
  [1, 0],
  [0, 0],
  [2, 1],
  [0, 0],
  [1, 1],
  [0, 0],
  [1, 3],
  [0, 0],
  [0, 0],
  [2, 0],
  [1, 0],
  [0, 1],
  [0, 0],
  [0, 2],
  [1, 0],
  [1, 2],
  [2, 1],
  [2, 0],
  [0, 1],
  [0, 0],
  [0, 0],
  [0, 0],
  [0, 0],
  [0, 0],
  [2, 1],
  [0, 0],
  [1, 0],
  [0, 0],
  [0, 0],
  [1, 1],
  [0, 0],
  [1, 0],
  [2, 0],
  [2, 1],
  [1, 0],
  [0, 0],
  [1, 1],
  [0, 1],
  [0, 0],
  [2, 0],
  [1, 1],
  [1, 0],
  [2, 1],
  [1, 0],
  [0, 0],
  [0, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [0, 0],
  [0, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [0, 0],
  [0, 0],
  [2, 1],
  [0, 0],
  [1, 0],
  [0, 0],
  [2, 0],
  [0, 0],
  [1, 0],
  [0, 0],
  [1, 1],
  [0, 1],
  [0, 1]],
 ['positif', 'negatif'])

In [19]:
df_hasil = pd.DataFrame(fitur_sentimen_all, columns=emosi)
df_hasil

     positif  negatif
0          0        0
1          0        0
2          0        0
3          0        0
4          1        0
..       ...      ...
193        1        0
194        0        0
195        1        1
196        0        1
197        0        1

[198 rows x 2 columns]